# Generated by Django 3.2.12 on 2022-05-05 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusName',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_direction', models.CharField(max_length=155)),
                ('bus_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
                ('disambiguator', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_sequence', models.IntegerField(unique=True)),
                ('period_name', models.CharField(default='', max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='bookinginfo.period')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('disambiguator', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=45)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='bookinginfo.busname')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endlocation', to='bookinginfo.locationdetail')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='bookinginfo.semester')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startlocation', to='bookinginfo.locationdetail')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='bookinginfo.year'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='bookinginfo.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='bookinginfo.user')),
            ],
        ),
    ]
