# Generated by Django 3.2.12 on 2022-05-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinginfo', '0004_auto_20220505_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busname',
            name='bus_number',
            field=models.IntegerField(unique=True),
        ),
    ]
